vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /uploads/posters
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/uploads/posters'
        picture_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /uploads/pictures
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/uploads/pictures'
